apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chabot-maysun-test-3
  janus-idp.io/tekton: chabot-maysun-test-3
  backstage.io/kubernetes-id: chabot-maysun-test-3
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: chabot-maysun-test-3
resources:
  - application-dev.yaml