apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chabot-maysun-test-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhdhpai-rolling-demo/chabot-maysun-test-3:25c2919f5557b2e0544542bc43f3627b5feff6f9@sha256:3c60b87bf4ebd934e0d9ce6c0440f098b6c999e058b999d17be2cbddff2887ef # use pre-built to bootstrap
          name: app-inference
