apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chabot-maysun-test-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chabot-maysun-test-3
  name: chabot-maysun-test-3
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chabot-maysun-test-3
